apiVersion: v2
name: windmill
type: application
version: 2.0.509
appVersion: 1.555.0
dependencies:
  - condition: postgresql.enabled
    name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.26.0  # Latest stable version
  - condition: hub-postgresql.enabled
    name: cloudnative-pg
    alias: hub-postgresql
    repository: https://cloudnative-pg.github.io/charts
    version: 0.26.0  # Latest stable version
  - condition: minio.enabled
    name: minio
    repository: https://charts.min.io/
    version: 5.4.0  # Latest stable version
deprecated: false
description: Windmill - Turn scripts into endpoints, workflows and UIs in minutes
home: https://www.windmill.dev/
icon: https://www.windmill.dev/img/windmill.svg
keywords:
  - windmill
  - scripts
  - flows
  - workflows
  - internal
  - apps
  - open-source
maintainers:
  - email: ruben@windmill.dev
    name: windmill
    url: https://www.windmill.dev/
sources:
  - https://github.com/windmill-labs/windmill-helm-charts.git
